export const precintList = [
  {
    value: "Adjuntas - 055",
    precint: "055",
    districtRep: 22,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "adjuntas",
  },
  {
    value: "Adjuntas - 111",
    precint: "111",
    districtRep: 23,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "adjuntas",
  },
  {
    value: "Aguada - 038",
    precint: "038",
    districtRep: 18,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "aguada",
  },
  {
    value: "Aguadilla - 035",
    precint: "035",
    districtRep: 17,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "aguadilla",
  },
  {
    value: "Aguadilla - 085",
    precint: "085",
    districtRep: 16,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "aguadilla",
  },
  {
    value: "Aguas Buenas - 081",
    precint: "081",
    districtRep: 5,
    districtSen: 1,
    districtSenName: "San Juan",
    municipality: "aguas buenas",
  },
  {
    value: "Aibonito - 069",
    precint: "069",
    districtRep: 27,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "aibonito",
  },
  {
    value: "Arecibo - 026",
    precint: "026",
    districtRep: 13,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "arecibo",
  },
  {
    value: "Arecibo - 027",
    precint: "027",
    districtRep: 14,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "arecibo",
  },
  {
    value: "Arroyo - 080",
    precint: "080",
    districtRep: 30,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "arroyo",
  },
  {
    value: "Añasco - 040",
    precint: "040",
    districtRep: 18,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "añasco",
  },
  {
    value: "Barceloneta - 025",
    precint: "025",
    districtRep: 13,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "barceloneta",
  },
  {
    value: "Barranquitas - 070",
    precint: "070",
    districtRep: 26,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "barranquitas",
  },
  {
    value: "Barranquitas - 071",
    precint: "071",
    districtRep: 28,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "barranquitas",
  },
  {
    value: "Bayamón - 010",
    precint: "010",
    districtRep: 7,
    districtSen: 2,
    districtSenName: "Bayamón",
    municipality: "bayamón",
  },
  {
    value: "Bayamón - 011",
    precint: "011",
    districtRep: 8,
    districtSen: 2,
    districtSenName: "Bayamón",
    municipality: "bayamón",
  },
  {
    value: "Bayamón - 012",
    precint: "012",
    districtRep: 9,
    districtSen: 2,
    districtSenName: "Bayamón",
    municipality: "bayamón",
  },
  {
    value: "Bayamón - 041",
    precint: "041",
    districtRep: 6,
    districtSen: 2,
    districtSenName: "Bayamón",
    municipality: "bayamón",
  },
  {
    value: "Cabo Rojo - 046",
    precint: "046",
    districtRep: 20,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "cabo rojo",
  },
  {
    value: "Caguas - 082",
    precint: "082",
    districtRep: 31,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "caguas",
  },
  {
    value: "Caguas - 083",
    precint: "083",
    districtRep: 32,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "caguas",
  },
  {
    value: "Camuy - 030",
    precint: "030",
    districtRep: 15,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "camuy",
  },
  {
    value: "Canóvanas - 104",
    precint: "104",
    districtRep: 37,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "canóvanas",
  },
  {
    value: "Canóvanas - 105",
    precint: "105",
    districtRep: 38,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "canóvanas",
  },
  {
    value: "Carolina - 106",
    precint: "106",
    districtRep: 38,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "carolina",
  },
  {
    value: "Carolina - 107",
    precint: "107",
    districtRep: 39,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "carolina",
  },
  {
    value: "Carolina - 108",
    precint: "108",
    districtRep: 40,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "carolina",
  },
  {
    value: "Cataño - 008",
    precint: "008",
    districtRep: 6,
    districtSen: 2,
    districtSenName: "Bayamón",
    municipality: "cataño",
  },
  {
    value: "Cataño - 009",
    precint: "009",
    districtRep: 10,
    districtSen: 2,
    districtSenName: "Bayamón",
    municipality: "cataño",
  },
  {
    value: "Cayey - 077",
    precint: "077",
    districtRep: 29,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "cayey",
  },
  {
    value: "Ceiba - 098",
    precint: "098",
    districtRep: 36,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "ceiba",
  },
  {
    value: "Ciales - 023",
    precint: "023",
    districtRep: 22,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "ciales",
  },
  {
    value: "Cidra - 076",
    precint: "076",
    districtRep: 29,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "cidra",
  },
  {
    value: "Coamo - 068",
    precint: "068",
    districtRep: 26,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "coamo",
  },
  {
    value: "Coamo - 075",
    precint: "075",
    districtRep: 27,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "coamo",
  },
  {
    value: "Comerío - 074",
    precint: "074",
    districtRep: 28,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "comerío",
  },
  {
    value: "Corozal - 072",
    precint: "072",
    districtRep: 28,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "corozal",
  },
  {
    value: "Corozal - 112",
    precint: "112",
    districtRep: 26,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "corozal",
  },
  {
    value: "Culebra - 097",
    precint: "097",
    districtRep: 36,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "culebra",
  },
  {
    value: "Dorado - 015",
    precint: "015",
    districtRep: 11,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "dorado",
  },
  {
    value: "Fajardo - 099",
    precint: "099",
    districtRep: 36,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "fajardo",
  },
  {
    value: "Florida - 024",
    precint: "024",
    districtRep: 13,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "florida",
  },
  {
    value: "Guayama - 079",
    precint: "079",
    districtRep: 30,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "guayama",
  },
  {
    value: "Guayanilla - 058",
    precint: "058",
    districtRep: 23,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "guayanilla",
  },
  {
    value: "Guaynabo - 006",
    precint: "006",
    districtRep: 5,
    districtSen: 1,
    districtSenName: "San Juan",
    municipality: "guaynabo",
  },
  {
    value: "Guaynabo - 007",
    precint: "007",
    districtRep: 6,
    districtSen: 2,
    districtSenName: "Bayamón",
    municipality: "guaynabo",
  },
  {
    value: "Gurabo - 084",
    precint: "084",
    districtRep: 31,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "gurabo",
  },
  {
    value: "Gurabo - 114",
    precint: "114",
    districtRep: 33,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "gurabo",
  },
  {
    value: "Guánica - 048",
    precint: "048",
    districtRep: 21,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "guánica",
  },
  {
    value: "Hatillo - 028",
    precint: "028",
    districtRep: 14,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "hatillo",
  },
  {
    value: "Hatillo - 029",
    precint: "029",
    districtRep: 15,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "hatillo",
  },
  {
    value: "Hormigueros - 045",
    precint: "045",
    districtRep: 20,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "hormigueros",
  },
  {
    value: "Humacao - 094",
    precint: "094",
    districtRep: 35,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "humacao",
  },
  {
    value: "Isabela - 032",
    precint: "032",
    districtRep: 16,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "isabela",
  },
  {
    value: "Jayuya - 056",
    precint: "056",
    districtRep: 22,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "jayuya",
  },
  {
    value: "Jayuya - 057",
    precint: "057",
    districtRep: 25,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "jayuya",
  },
  {
    value: "Juana Díaz - 063",
    precint: "063",
    districtRep: 25,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "juana díaz",
  },
  {
    value: "Juana Díaz - 064",
    precint: "064",
    districtRep: 27,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "juana díaz",
  },
  {
    value: "Juncos - 088",
    precint: "088",
    districtRep: 33,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "juncos",
  },
  {
    value: "Lajas - 047",
    precint: "047",
    districtRep: 21,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "lajas",
  },
  {
    value: "Lares - 053",
    precint: "053",
    districtRep: 22,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "lares",
  },
  {
    value: "Las Marias - 034",
    precint: "034",
    districtRep: 21,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "las marias",
  },
  {
    value: "Las Piedras - 089",
    precint: "089",
    districtRep: 33,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "las piedras",
  },
  {
    value: "Las Piedras - 090",
    precint: "090",
    districtRep: 35,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "las piedras",
  },
  {
    value: "Loíza - 103",
    precint: "103",
    districtRep: 37,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "loíza",
  },
  {
    value: "Luquillo - 100",
    precint: "100",
    districtRep: 36,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "luquillo",
  },
  {
    value: "Manatí - 021",
    precint: "021",
    districtRep: 12,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "manatí",
  },
  {
    value: "Manatí - 022",
    precint: "022",
    districtRep: 13,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "manatí",
  },
  {
    value: "Maricao - 050",
    precint: "050",
    districtRep: 21,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "maricao",
  },
  {
    value: "Maunabo - 092",
    precint: "092",
    districtRep: 34,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "maunabo",
  },
  {
    value: "Mayagüez - 042",
    precint: "042",
    districtRep: 19,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "mayagüez",
  },
  {
    value: "Moca - 036",
    precint: "036",
    districtRep: 17,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "moca",
  },
  {
    value: "Moca - 037",
    precint: "037",
    districtRep: 18,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "moca",
  },
  {
    value: "Morovis - 020",
    precint: "020",
    districtRep: 12,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "morovis",
  },
  {
    value: "Naguabo - 095",
    precint: "095",
    districtRep: 35,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "naguabo",
  },
  {
    value: "Naranjito - 073",
    precint: "073",
    districtRep: 28,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "naranjito",
  },
  {
    value: "Orocovis - 066",
    precint: "066",
    districtRep: 26,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "orocovis",
  },
  {
    value: "Patillas - 091",
    precint: "091",
    districtRep: 34,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "patillas",
  },
  {
    value: "Peñuelas - 059",
    precint: "059",
    districtRep: 23,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "peñuelas",
  },
  {
    value: "Ponce - 060",
    precint: "060",
    districtRep: 23,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "ponce",
  },
  {
    value: "Ponce - 061",
    precint: "061",
    districtRep: 24,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "ponce",
  },
  {
    value: "Ponce - 062",
    precint: "062",
    districtRep: 25,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "ponce",
  },
  {
    value: "Quebradillas - 031",
    precint: "031",
    districtRep: 15,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "quebradillas",
  },
  {
    value: "Rincón - 039",
    precint: "039",
    districtRep: 18,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "rincón",
  },
  {
    value: "Río Grande - 101",
    precint: "101",
    districtRep: 36,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "río grande",
  },
  {
    value: "Río Grande - 102",
    precint: "102",
    districtRep: 37,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "río grande",
  },
  {
    value: "Salinas - 078",
    precint: "078",
    districtRep: 30,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "salinas",
  },
  {
    value: "San Germán - 043",
    precint: "043",
    districtRep: 19,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "san germán",
  },
  {
    value: "San Germán - 044",
    precint: "044",
    districtRep: 20,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "san germán",
  },
  {
    value: "San Juan - 001",
    precint: "001",
    districtRep: 1,
    districtSen: 1,
    districtSenName: "San Juan",
    municipality: "san juan",
  },
  {
    value: "San Juan - 002",
    precint: "002",
    districtRep: 2,
    districtSen: 1,
    districtSenName: "San Juan",
    municipality: "san juan",
  },
  {
    value: "San Juan - 003",
    precint: "003",
    districtRep: 3,
    districtSen: 1,
    districtSenName: "San Juan",
    municipality: "san juan",
  },
  {
    value: "San Juan - 004",
    precint: "004",
    districtRep: 4,
    districtSen: 1,
    districtSenName: "San Juan",
    municipality: "san juan",
  },
  {
    value: "San Juan - 005",
    precint: "005",
    districtRep: 5,
    districtSen: 1,
    districtSenName: "San Juan",
    municipality: "san juan",
  },
  {
    value: "San Lorenzo - 086",
    precint: "086",
    districtRep: 33,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "san lorenzo",
  },
  {
    value: "San Lorenzo - 087",
    precint: "087",
    districtRep: 34,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "san lorenzo",
  },
  {
    value: "San Sebastián - 033",
    precint: "033",
    districtRep: 16,
    districtSen: 4,
    districtSenName: "Mayagüez",
    municipality: "san sebastián",
  },
  {
    value: "Santa Isabel - 067",
    precint: "067",
    districtRep: 27,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "santa isabel",
  },
  {
    value: "Santa Isabel - 113",
    precint: "113",
    districtRep: 30,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "santa isabel",
  },
  {
    value: "Sábana Grande - 049",
    precint: "049",
    districtRep: 21,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "sábana grande",
  },
  {
    value: "Toa Alta - 013",
    precint: "013",
    districtRep: 9,
    districtSen: 2,
    districtSenName: "Bayamón",
    municipality: "toa alta",
  },
  {
    value: "Toa Baja - 014",
    precint: "014",
    districtRep: 10,
    districtSen: 2,
    districtSenName: "Bayamón",
    municipality: "toa baja",
  },
  {
    value: "Trujillo Alto - 109",
    precint: "109",
    districtRep: 38,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "trujillo alto",
  },
  {
    value: "Trujillo Alto - 110",
    precint: "110",
    districtRep: 39,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "trujillo alto",
  },
  {
    value: "Utuado - 054",
    precint: "054",
    districtRep: 22,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "utuado",
  },
  {
    value: "Vega Alta - 016",
    precint: "016",
    districtRep: 11,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "vega alta",
  },
  {
    value: "Vega Alta - 017",
    precint: "017",
    districtRep: 12,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "vega alta",
  },
  {
    value: "Vega Baja - 018",
    precint: "018",
    districtRep: 11,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "vega baja",
  },
  {
    value: "Vega Baja - 019",
    precint: "019",
    districtRep: 12,
    districtSen: 3,
    districtSenName: "Arecibo",
    municipality: "vega baja",
  },
  {
    value: "Vieques - 096",
    precint: "096",
    districtRep: 36,
    districtSen: 8,
    districtSenName: "Carolina",
    municipality: "vieques",
  },
  {
    value: "Villalba - 065",
    precint: "065",
    districtRep: 26,
    districtSen: 6,
    districtSenName: "Guayama",
    municipality: "villalba",
  },
  {
    value: "Yabucoa - 093",
    precint: "093",
    districtRep: 34,
    districtSen: 7,
    districtSenName: "Humacao",
    municipality: "yabucoa",
  },
  {
    value: "Yauco - 051",
    precint: "051",
    districtRep: 21,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "yauco",
  },
  {
    value: "Yauco - 052",
    precint: "052",
    districtRep: 23,
    districtSen: 5,
    districtSenName: "Ponce",
    municipality: "yauco",
  },
]

export type TourType = {
  selector: string
  content: string
}

const StateBallotTour = [
  {
    selector: '[data-tour-id="governor-header"]',
    content:
      "Tienes derecho a votar por un (1) candidato(a) a gobernador(a) de cualquier partido, candidatura independiente o nominación directa.",
  },
  {
    selector: '[data-tour-id="commissioner-resident-header"]',
    content:
      "Tienes derecho a votar un (1) candidato(a) a comisionado(a) residente de cualquier partido, candidatura independiente o nominación directa.",
  },
]

const MunicipalBallotTour = [
  {
    selector: '[data-tour-id="mayor-header"]',
    content:
      "Tienes derecho a votar por un (1) candidato(a) a alcalde(sa) de cualquier partido, candidatura independiente o nominación directa.",
  },
  {
    selector: '[data-tour-id="municipal-legislator-header"]',
    content:
      "Tienes derecho a votar por la cantidad máxima de legisladores(as) municipales en la papeleta de cualquier partido, candidatura independiente o nominación directa.",
  },
]

const LegislativeBallotTour = [
  {
    selector: '[data-tour-id="district-representative-header"]',
    content:
      "Tienes derecho a votar por un (1) candidato(a) a representante por distrito de cualquier partido, candidatura independiente o nominación directa.",
    position: "top",
  },
  {
    selector: '[data-tour-id="district-senator-header"]',
    content:
      "Tienes derecho a votar por dos (2) candidatos(as) a senador(a) por distrito de cualquier partido, candidatura independiente o nominación directa.",
    position: "top",
  },
  {
    selector: '[data-tour-id="at-large-representative-header"]',
    content:
      "Tienes derecho a votar por un (1) candidato(a) a representante por acumulación de cualquier partido, candidatura independiente o nominación directa.",
    position: "top",
  },
  {
    selector: '[data-tour-id="at-large-senator-header"]',
    content:
      "Tienes derecho a votar por un (1) candidato(a) a senador(a) por acumulación de cualquier partido, candidatura independiente o nominación directa.",
    position: "top",
  },
]

export const Tours = {
  state: StateBallotTour,
  municipal: MunicipalBallotTour,
  legislative: LegislativeBallotTour,
}

export const precinctMap = {
  "100": "Luquillo",
  "101": "Río Grande",
  "102": "Río Grande",
  "103": "Loíza",
  "104": "Canóvanas",
  "105": "Canóvanas",
  "106": "Carolina",
  "107": "Carolina",
  "108": "Carolina",
  "109": "Trujillo Alto",
  "110": "Trujillo Alto",
  "111": "Adjuntas",
  "112": "Corozal",
  "113": "Santa Isabel",
  "114": "Gurabo",
  "055": "Adjuntas",
  "038": "Aguada",
  "035": "Aguadilla",
  "085": "Aguadilla",
  "081": "Aguas Buenas",
  "069": "Aibonito",
  "026": "Arecibo",
  "027": "Arecibo",
  "080": "Arroyo",
  "040": "Añasco",
  "025": "Barceloneta",
  "070": "Barranquitas",
  "071": "Barranquitas",
  "010": "Bayamón",
  "011": "Bayamón",
  "012": "Bayamón",
  "041": "Bayamón",
  "046": "Cabo Rojo",
  "082": "Caguas",
  "083": "Caguas",
  "030": "Camuy",
  "008": "Cataño",
  "009": "Cataño",
  "077": "Cayey",
  "098": "Ceiba",
  "023": "Ciales",
  "076": "Cidra",
  "068": "Coamo",
  "075": "Coamo",
  "074": "Comerío",
  "072": "Corozal",
  "097": "Culebra",
  "015": "Dorado",
  "099": "Fajardo",
  "024": "Florida",
  "079": "Guayama",
  "058": "Guayanilla",
  "006": "Guaynabo",
  "007": "Guaynabo",
  "084": "Gurabo",
  "048": "Guánica",
  "028": "Hatillo",
  "029": "Hatillo",
  "045": "Hormigueros",
  "094": "Humacao",
  "032": "Isabela",
  "056": "Jayuya",
  "057": "Jayuya",
  "063": "Juana Díaz",
  "064": "Juana Díaz",
  "088": "Juncos",
  "047": "Lajas",
  "053": "Lares",
  "034": "Las Marias",
  "089": "Las Piedras",
  "090": "Las Piedras",
  "021": "Manatí",
  "022": "Manatí",
  "050": "Maricao",
  "092": "Maunabo",
  "042": "Mayagüez",
  "036": "Moca",
  "037": "Moca",
  "020": "Morovis",
  "095": "Naguabo",
  "073": "Naranjito",
  "066": "Orocovis",
  "091": "Patillas",
  "059": "Peñuelas",
  "060": "Ponce",
  "061": "Ponce",
  "062": "Ponce",
  "031": "Quebradillas",
  "039": "Rincón",
  "078": "Salinas",
  "043": "San Germán",
  "044": "San Germán",
  "001": "San Juan",
  "002": "San Juan",
  "003": "San Juan",
  "004": "San Juan",
  "005": "San Juan",
  "086": "San Lorenzo",
  "087": "San Lorenzo",
  "033": "San Sebastián",
  "067": "Santa Isabel",
  "049": "Sábana Grande",
  "013": "Toa Alta",
  "014": "Toa Baja",
  "054": "Utuado",
  "016": "Vega Alta",
  "017": "Vega Alta",
  "018": "Vega Baja",
  "019": "Vega Baja",
  "096": "Vieques",
  "065": "Villalba",
  "093": "Yabucoa",
  "051": "Yauco",
  "052": "Yauco",
}
